import { useListArtifacts, useDeleteArtifact } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Box, Trash2, FileText, Code, Image } from "lucide-react";
import { format } from "date-fns";

const typeIcon: Record<string, React.ReactNode> = {
  code: <Code className="w-4 h-4" />,
  text: <FileText className="w-4 h-4" />,
  image: <Image className="w-4 h-4" />,
};

function formatBytes(b: number | null | undefined) {
  if (!b) return "—";
  if (b < 1024) return `${b}B`;
  if (b < 1048576) return `${(b / 1024).toFixed(1)}KB`;
  return `${(b / 1048576).toFixed(1)}MB`;
}

export default function Artifacts() {
  const { data: artifacts, isLoading } = useListArtifacts();
  const deleteArtifact = useDeleteArtifact();

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8 font-mono">
      <div className="flex items-center justify-between border-b border-border pb-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tighter">Artifacts</h1>
          <p className="text-muted-foreground mt-1 text-sm">Files and outputs generated by agents.</p>
        </div>
        <Box className="w-8 h-8 text-primary opacity-50" />
      </div>

      {isLoading ? (
        <div className="text-primary animate-pulse">Loading artifacts...</div>
      ) : !artifacts?.length ? (
        <div className="text-center py-16 text-muted-foreground">
          <Box className="w-12 h-12 mx-auto mb-4 opacity-20" />
          <p>No artifacts yet. Run an agent task to generate output.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {artifacts.map((artifact) => (
            <Card key={artifact.id} className="bg-card border-border shadow-none">
              <CardContent className="p-4">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-3 min-w-0">
                    <div className="text-primary mt-0.5 shrink-0">
                      {typeIcon[artifact.artifactType] ?? <FileText className="w-4 h-4" />}
                    </div>
                    <div className="min-w-0">
                      <div className="font-medium text-sm truncate">{artifact.title}</div>
                      <div className="text-xs text-muted-foreground mt-1 space-x-2">
                        <span>by {artifact.creatorAgent}</span>
                        <span>·</span>
                        <span>{formatBytes(artifact.sizeBytes)}</span>
                        <span>·</span>
                        <span>v{artifact.version}</span>
                      </div>
                    </div>
                  </div>
                  <Button
                    variant="ghost" size="icon"
                    onClick={() => deleteArtifact.mutate({ id: artifact.id })}
                    className="shrink-0"
                  >
                    <Trash2 className="w-3.5 h-3.5 text-destructive" />
                  </Button>
                </div>

                {artifact.content && (
                  <div className="mt-3 bg-background rounded border border-border p-2">
                    <pre className="text-xs text-muted-foreground whitespace-pre-wrap line-clamp-4">
                      {artifact.content}
                    </pre>
                  </div>
                )}

                <div className="flex items-center justify-between mt-3">
                  <Badge variant="outline" className="text-xs">{artifact.artifactType}</Badge>
                  <span className="text-xs text-muted-foreground">
                    {format(new Date(artifact.createdAt), "MMM d, HH:mm")}
                  </span>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
