import { useGetDashboardSummary } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, Box, CheckSquare, MessageSquare } from "lucide-react";
import { format } from "date-fns";

export default function Dashboard() {
  const { data: summary, isLoading, error } = useGetDashboardSummary();

  if (isLoading) {
    return <div className="p-4 md:p-8 text-primary font-mono animate-pulse">Loading telemetry...</div>;
  }

  if (error) {
    return <div className="p-4 md:p-8 text-destructive font-mono">Error loading telemetry data.</div>;
  }

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6 font-mono">
      <div className="flex items-start justify-between border-b border-border pb-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold tracking-tighter text-foreground">Mission Control</h1>
          <p className="text-muted-foreground mt-1 text-xs md:text-sm">Platform telemetry and agent status.</p>
        </div>
        <div className="flex items-center gap-1.5 text-xs md:text-sm shrink-0 ml-4">
          <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
          <span className="text-primary hidden sm:inline">OPERATIONAL</span>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-1 space-y-0 pt-3 px-3">
            <CardTitle className="text-xs font-medium text-muted-foreground">Active Tasks</CardTitle>
            <Activity className="w-3.5 h-3.5 text-primary" />
          </CardHeader>
          <CardContent className="px-3 pb-3">
            <div className="text-xl md:text-2xl font-bold text-foreground">{summary?.activeTasks ?? 0}</div>
            <p className="text-xs text-muted-foreground mt-0.5">
              {summary?.completedTasks ?? 0} done · {summary?.failedTasks ?? 0} failed
            </p>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-1 space-y-0 pt-3 px-3">
            <CardTitle className="text-xs font-medium text-muted-foreground">Artifacts</CardTitle>
            <Box className="w-3.5 h-3.5 text-primary" />
          </CardHeader>
          <CardContent className="px-3 pb-3">
            <div className="text-xl md:text-2xl font-bold text-foreground">{summary?.totalArtifacts ?? 0}</div>
            <p className="text-xs text-muted-foreground mt-0.5">Generated by agents</p>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-1 space-y-0 pt-3 px-3">
            <CardTitle className="text-xs font-medium text-muted-foreground">Sessions</CardTitle>
            <MessageSquare className="w-3.5 h-3.5 text-primary" />
          </CardHeader>
          <CardContent className="px-3 pb-3">
            <div className="text-xl md:text-2xl font-bold text-foreground">{summary?.totalSessions ?? 0}</div>
            <p className="text-xs text-muted-foreground mt-0.5">Active dialogues</p>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-1 space-y-0 pt-3 px-3">
            <CardTitle className="text-xs font-medium text-muted-foreground">Plans</CardTitle>
            <CheckSquare className="w-3.5 h-3.5 text-primary" />
          </CardHeader>
          <CardContent className="px-3 pb-3">
            <div className="text-xl md:text-2xl font-bold text-foreground">{summary?.totalPlans ?? 0}</div>
            <p className="text-xs text-muted-foreground mt-0.5">Total workflows</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Recent Events */}
        <Card className="lg:col-span-2 bg-card border-border shadow-none">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="text-base">Recent Events</CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4">
            <div className="space-y-3">
              {summary?.recentEvents?.length ? (
                summary.recentEvents.map((event) => (
                  <div key={event.id} className="flex items-start justify-between border-b border-border/50 pb-3 last:border-0 last:pb-0 gap-2">
                    <div className="min-w-0">
                      <div className="flex items-center flex-wrap gap-1">
                        <span className="text-xs font-bold text-primary uppercase">[{event.entityType}]</span>
                        <span className="text-xs text-foreground truncate">{event.description}</span>
                      </div>
                      <div className="text-xs text-muted-foreground mt-0.5">{event.eventType}</div>
                    </div>
                    <span className="text-xs text-muted-foreground whitespace-nowrap shrink-0">
                      {format(new Date(event.createdAt), "HH:mm")}
                    </span>
                  </div>
                ))
              ) : (
                <div className="text-sm text-muted-foreground py-4 text-center">No recent events.</div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Provider Health */}
        <Card className="bg-card border-border shadow-none">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="text-base">Provider Status</CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4">
            <div className="space-y-3">
              {summary?.providerHealth?.length ? (
                summary.providerHealth.map((provider) => (
                  <div key={provider.id} className="flex items-center justify-between">
                    <div className="flex items-center gap-2 min-w-0">
                      <div className={`w-2 h-2 rounded-full shrink-0 ${provider.isHealthy ? "bg-primary" : "bg-destructive"}`} />
                      <span className="text-sm font-medium truncate">{provider.name}</span>
                    </div>
                    <span className="text-xs text-muted-foreground shrink-0 ml-2">
                      {provider.latencyMs ? `${provider.latencyMs}ms` : "N/A"}
                    </span>
                  </div>
                ))
              ) : (
                <div className="text-sm text-muted-foreground py-4 text-center">No active providers.</div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
