import { useGetDashboardSummary } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, Box, CheckSquare, MessageSquare, AlertCircle } from "lucide-react";
import { format } from "date-fns";

export default function Dashboard() {
  const { data: summary, isLoading, error } = useGetDashboardSummary();

  if (isLoading) {
    return <div className="p-8 text-primary font-mono animate-pulse">Loading telemetry...</div>;
  }

  if (error) {
    return <div className="p-8 text-destructive font-mono">Error loading telemetry data.</div>;
  }

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 font-mono">
      <div className="flex items-center justify-between border-b border-border pb-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tighter text-foreground">Mission Control</h1>
          <p className="text-muted-foreground mt-1 text-sm">Platform telemetry and agent status overview.</p>
        </div>
        <div className="flex items-center space-x-2 text-sm">
          <span className="text-muted-foreground">Status:</span>
          <span className="text-primary flex items-center">
            <span className="w-2 h-2 rounded-full bg-primary animate-pulse mr-2" />
            OPERATIONAL
          </span>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium text-muted-foreground">Active Tasks</CardTitle>
            <Activity className="w-4 h-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">{summary?.activeTasks || 0}</div>
            <p className="text-xs text-muted-foreground mt-1">
              {summary?.completedTasks || 0} completed · {summary?.failedTasks || 0} failed
            </p>
          </CardContent>
        </Card>
        
        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Artifacts</CardTitle>
            <Box className="w-4 h-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">{summary?.totalArtifacts || 0}</div>
            <p className="text-xs text-muted-foreground mt-1">Generated by agents</p>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium text-muted-foreground">Chat Sessions</CardTitle>
            <MessageSquare className="w-4 h-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">{summary?.totalSessions || 0}</div>
            <p className="text-xs text-muted-foreground mt-1">Active dialogues</p>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-none">
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium text-muted-foreground">Execution Plans</CardTitle>
            <CheckSquare className="w-4 h-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">{summary?.totalPlans || 0}</div>
            <p className="text-xs text-muted-foreground mt-1">Total workflows</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Recent Events */}
        <Card className="col-span-2 bg-card border-border shadow-none">
          <CardHeader>
            <CardTitle className="text-lg">Recent Events</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {summary?.recentEvents && summary.recentEvents.length > 0 ? (
                summary.recentEvents.map((event) => (
                  <div key={event.id} className="flex items-start justify-between border-b border-border/50 pb-4 last:border-0 last:pb-0">
                    <div>
                      <div className="flex items-center">
                        <span className="text-xs font-bold text-primary mr-2 uppercase">[{event.entityType}]</span>
                        <span className="text-sm text-foreground">{event.description}</span>
                      </div>
                      <div className="text-xs text-muted-foreground mt-1">
                        ID: {event.entityId} • {event.eventType}
                      </div>
                    </div>
                    <span className="text-xs text-muted-foreground whitespace-nowrap">
                      {format(new Date(event.createdAt), "HH:mm:ss")}
                    </span>
                  </div>
                ))
              ) : (
                <div className="text-sm text-muted-foreground py-4 text-center">No recent events.</div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Provider Health */}
        <Card className="bg-card border-border shadow-none">
          <CardHeader>
            <CardTitle className="text-lg">Provider Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {summary?.providerHealth && summary.providerHealth.length > 0 ? (
                summary.providerHealth.map((provider) => (
                  <div key={provider.id} className="flex items-center justify-between">
                    <div className="flex items-center">
                      {provider.isHealthy ? (
                        <div className="w-2 h-2 rounded-full bg-primary mr-2" />
                      ) : (
                        <div className="w-2 h-2 rounded-full bg-destructive mr-2" />
                      )}
                      <span className="text-sm font-medium">{provider.name}</span>
                    </div>
                    <div className="text-xs text-muted-foreground">
                      {provider.latencyMs ? `${provider.latencyMs}ms` : "N/A"}
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-sm text-muted-foreground py-4 text-center">No active providers.</div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
